// src/app/api/explain/route.ts
//
// GET /api/explain?team=Brazil&status=HANGING_ON
//
// Returns a plain-English explanation of a team's qualification status,
// generated by Groq (llama-3.3-70b-versatile) using the exact system prompt
// from Section 10 of STILLIN_MASTER.md.
//
// WHY WE CACHE: Groq costs money and the explanation for a given team+status
// combination doesn't change — "Brazil is HANGING_ON" means the same thing
// regardless of when it's asked. The UNIQUE(team, status) constraint on
// `ai_explanations` guarantees we never generate twice for the same state.
// A cache hit is instantaneous and free; a miss triggers one Groq call then
// is never triggered again for that pair.
//
// NOTE: Section 9 says to stream the response back. This implementation returns
// plain JSON instead (per task spec). If streaming is needed later, switch to
// a ReadableStream response using the Groq streaming API.
//
// Per Section 9 & 10 of STILLIN_MASTER.md.

import { NextRequest, NextResponse } from "next/server";
import { supabaseServer } from "@/lib/supabase-server";

const GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions";
const GROQ_MODEL = "llama-3.3-70b-versatile";
const REQUEST_TIMEOUT_MS = 10_000;

// Valid status values — used to validate the query param and build context strings.
const VALID_STATUSES = ["THROUGH", "HANGING_ON", "IN_DANGER", "OUT"] as const;
type Status = (typeof VALID_STATUSES)[number];

// Minimal type for the Groq chat completion response we care about.
type GroqResponse = {
  choices: Array<{
    message: {
      content: string;
    };
  }>;
};

// Produces a one-sentence context string for the prompt's {CONTEXT} slot.
// Keeps the model grounded in what the status actually means right now
// without repeating all the tiebreaker logic.
function buildContext(status: Status, team: string): string {
  switch (status) {
    case "THROUGH":
      return `${team} have already secured their place in the knockout round.`;
    case "HANGING_ON":
      return `${team} are currently ranked as one of the top 8 third-placed teams, which is enough to qualify — but other results could still push them out.`;
    case "IN_DANGER":
      return `${team} are a third-placed team but currently ranked outside the top 8 third-placed teams, so they would not go through if the group stage ended now.`;
    case "OUT":
      return `${team} have been eliminated and cannot qualify for the knockout round.`;
  }
}

// The exact system prompt from Section 10. {TEAM}, {STATUS}, and {CONTEXT} are
// substituted at call time. Do not change without approval from STILLIN_MASTER.md.
function buildSystemPrompt(team: string, status: Status): string {
  const context = buildContext(status, team);
  return `You explain World Cup 2026 qualification to people who barely follow football.

Rules:
- Maximum 3 sentences
- Zero football jargon — no "clean sheet", "aggregate", "xG", etc.
- No statistics or numbers unless absolutely essential
- Speak like a friend explaining it at a pub
- End every explanation with one word: either "RELAX" or "NERVOUS"
- That final word is on its own line

The team's current status is: ${status}
The team's name is: ${team}
Additional context: ${context}`;
}

export async function GET(request: NextRequest): Promise<NextResponse> {
  const { searchParams } = request.nextUrl;
  const team = searchParams.get("team")?.trim();
  const statusParam = searchParams.get("status")?.trim();

  // --- Validate query params ---
  if (!team) {
    return NextResponse.json(
      { error: "Missing required query parameter: team" },
      { status: 400 },
    );
  }

  if (!statusParam) {
    return NextResponse.json(
      { error: "Missing required query parameter: status" },
      { status: 400 },
    );
  }

  if (!VALID_STATUSES.includes(statusParam as Status)) {
    return NextResponse.json(
      { error: `Invalid status. Must be one of: ${VALID_STATUSES.join(", ")}` },
      { status: 400 },
    );
  }

  const status = statusParam as Status;

  try {
    // --- 1. Check for a cached explanation first ---
    const { data: cached, error: selectError } = await supabaseServer
      .from("ai_explanations")
      .select("explanation")
      .eq("team", team)
      .eq("status", status)
      .limit(1);

    if (selectError) {
      throw new Error(`Supabase read failed: ${selectError.message}`);
    }

    if (cached && cached.length > 0) {
      return NextResponse.json({
        explanation: cached[0].explanation as string,
        cached: true,
      });
    }

    // --- 2. Cache miss: call Groq ---
    const apiKey = process.env.GROQ_API_KEY;
    if (!apiKey) {
      throw new Error("GROQ_API_KEY is not set — cannot call Groq API.");
    }

    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);

    let groqData: GroqResponse;
    try {
      const groqRes = await fetch(GROQ_API_URL, {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${apiKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: GROQ_MODEL,
          messages: [
            { role: "system", content: buildSystemPrompt(team, status) },
            { role: "user", content: "Generate the explanation now." },
          ],
          max_tokens: 150,
          temperature: 0.7,
        }),
        signal: controller.signal,
      });

      if (!groqRes.ok) {
        throw new Error(
          `Groq API returned HTTP ${groqRes.status} ${groqRes.statusText}`,
        );
      }

      groqData = (await groqRes.json()) as GroqResponse;
    } catch (err) {
      if (err instanceof Error && err.name === "AbortError") {
        throw new Error(`Groq API timed out after ${REQUEST_TIMEOUT_MS}ms.`);
      }
      throw err;
    } finally {
      clearTimeout(timeout);
    }

    const explanation = groqData.choices?.[0]?.message?.content?.trim();
    if (!explanation) {
      throw new Error("Groq returned an empty response.");
    }

    // --- 3. Save to cache so this pair is never generated again ---
    // ON CONFLICT DO NOTHING handles the rare race where two requests hit the
    // cache miss simultaneously — the second insert is silently dropped.
    const { error: insertError } = await supabaseServer
      .from("ai_explanations")
      .insert({ team, status, explanation });

    // A duplicate key error here means a concurrent request already inserted —
    // not a real failure. Any other insert error is worth surfacing.
    if (insertError && !insertError.message.includes("duplicate")) {
      throw new Error(`Supabase insert failed: ${insertError.message}`);
    }

    return NextResponse.json({ explanation, cached: false });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unexpected error";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
